### ISSUE TITLE
Set de tenis

### ISSUE THREAD

**Issue by rpinedat** [rpinedat/python-project#12]
En el programa 1_19 set de tenis usando flake 8 no marca ningún error pero en los warnings de Pycharm dice lo siguiente: "Simplify chained comparison" en las líneas 21 y 24. Puedo dejarlo así o ¿Cómo podría corregirlo?

**Comment by lunabytes** [comment]
Puedes dejarlo así, pero si quieres corregirlo puedes simplificar las comparaciones o agruparlas.

**Comment by rpinedat** [comment]
coloqué paréntesis y ya no marcó error, gracias
