### ISSUE TITLE
Posible Solución

### ISSUE THREAD

**Issue by lunabytes** [rpinedat/python-project#6]
https://github.com/rpinedat/python-project/blob/8300b07552bca94eead9ba57a408dd6d393f94c6/1_7Hora_futura.py#L2

Agrega en este caso una validación para el residuo creo que sería la solución más sencilla.

**Comment by rpinedat** [comment]
QUé devuelve divmode cuando el divisor es mas grande que el dividendo?

**Comment by lunabytes** [comment]
Te devuelve 0 como resultado de la división y te devuelve el valor del dividendo como residuo.

**Comment by rpinedat** [comment]
Perfecto, gracias
